import admin from "./admin.model.js";
import attribute_values from "./attribute_values.model.js";
import banners from "./banners.model.js";
import brands from "./brands.model.js";
import carts from "./carts.model.js";
import categories from "./categories.model.js";
import cms_pages from "./cms_pages.model.js";
import cod_pincodes from "./cod_pincodes.model.js";
import company_addresses from "./company_addresses.model.js";
import countries from "./countries.model.js";
import delivery_addresses from "./delivery_addresses.model.js";
import email_templates from "./email_templates.model.js";
import failed_jobs from "./failed_job.model.js";
import logos from "./logos.model.js";
import migrations from "./migrations.model.js";
import newsletter_subscribers from "./newsletter_subscribers.model.js";
import oauth_access_tokens from "./oauth_access_tokens.model.js";
import oauth_auth_codes from "./oauth_auth_codes.model.js";
import oauth_clients from "./oauth_clients.model.js";
import oauth_personal_access_clients from "./oauth_personal_access_clients.model.js";
import oauth_refresh_tokens from "./oauth_refresh_tokens.model.js";
import orders_item_statuses from "./order_item_statuses.model.js";
import orders_statuses from "./order_statuses.model.js";
import orders from "./orders.model.js";
import orders_logs from "./orders_logs.model.js";
import orders_products from "./orders_products.model.js";
import password_resets from "./password_resets.model.js";
// import pay_fast_logs from "./pay_fast_logs.model.js";
import payments from "./payments.model.js";
import personal_access_tokens from "./personal_access_tokens.model.js";
import prepaid_pincodes from "./prepaid_pincodes.model.js";
import product_attribute from "./product_attribute.model.js";
import product_filters from "./products_filters.model.js";
import product_filters_values from "./products_filters_values.model.js";
import products_images from "./products_images.model.js";
import products from './products.model.js';
import purchases from "./purchases.model.js";
import sections from "./sections.model.js";
import users from "./users.model.js";
import vendors from "./vendors.model.js";
// import vendors_bank_details from "./vendors_bank_details.model.js";
import recently_viewed_products from "./recently_viewed_products.model.js";
import ratings from "./ratings.model.js";
import wishlists from "./wishlists.model.js";
import return_orders from "./return_orders.model.js";
import rating_images from "./rating_images.model.js";
import transactions from "./transection.model.js";

// export const Admin = admin;
// export const attributeValues = attribute_values;
export const Banners = banners;
export const Brand = brands;
export const Carts = carts;
export const Categories = categories;
// export const cmsPages = cms_pages;
export const codPincodes = cod_pincodes;
export const companyAddresses = company_addresses;
export const Countries = countries;
export const deliveryAddresses = delivery_addresses;
// export const emailTemplates = email_templates;
// export const failedJob = failed_jobs;
export const Logos = logos;
// export const Migration = migrations;
// export const newsLetterSubscribers = newsletter_subscribers;
// export const oauthAccessTokens = oauth_access_tokens;
// export const oauthAuthCodes = oauth_auth_codes;
// export const oauthClients = oauth_clients;
// export const oauthPersonalAccessClient = oauth_personal_access_clients;
// export const oauthRefreshToken = oauth_refresh_tokens;
export const orderItemStatuses=orders_item_statuses;
export const orderStatuses =orders_statuses;
export const orderLogs=orders_logs;
export const orderProduct=orders_products;
export const Orders=orders;
export const passwordResets = password_resets;
// export const payFastLogs = pay_fast_logs;
// export const Payment=payments;
// export const personalAccessToken=personal_access_tokens;
export const productAttribute=product_attribute;
export const productFilterValue=product_filters_values;
export const productFilter=product_filters;
export const productImage=products_images;
export const Product=products;
export const prepaidPincodes = prepaid_pincodes;
export const Rating=ratings;
export const ratingImage=rating_images;
export const recently_viewed_product=recently_viewed_products;
export const returnOrders=return_orders;
export const Sections = sections;
export const User = users;
export const Vendor = vendors;
// export const vendorBankDetail = vendors_bank_details;
export const Wishlist=wishlists;
export const transaction=transactions;


